class Lexicon:
    bomb_collected = "Bombas recogídas"
    boxes_collected = "Número de cuadros recogidos:"
    boxes_remaining = "Número de cuadros restantes:"
    boxes_to_collect = "Número de cuadros por recoger:"
    instructions = "Instrucciones:"
    no = "No"
    results = 'Resultados'
    round_history = "Historial de rondas"
    round_number = "Ronda N."
    round_payoff = "Pago por ronda"
    solve = "Resolver"
    start = "Empezar"
    stop = "Stop"
    yes = "Sí"
    your_decision = "Su decisión"
